# Generated by Django 5.1.4 on 2025-01-15 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devTools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devtool',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='devtool',
            name='kind',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='devtool',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
