# Generated by Django 5.1.4 on 2025-01-09 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=100)),
                ('actors', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=50)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=1)),
                ('runtime', models.PositiveIntegerField()),
                ('review_content', models.TextField()),
                ('release_year', models.PositiveIntegerField()),
            ],
        ),
    ]
