# Generated by Django 5.1.4 on 2025-01-14 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devTools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='아이디어명')),
                ('image', models.ImageField(blank=True, upload_to='posts/%Y%m%d', verbose_name='Image')),
                ('content', models.TextField(verbose_name='아이디어 설명')),
                ('interest', models.IntegerField(default=0, verbose_name='아이디어 관심도')),
                ('is_starred', models.BooleanField(default=False)),
                ('devtool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devTools.devtool')),
            ],
        ),
    ]
