# Generated by Django 5.1.4 on 2025-01-15 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0001_initial'),
    ]

    operations = [
    ]
