# Generated by Django 5.1.4 on 2025-01-15 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0002_idea_created_at_idea_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='updated_at',
        ),
    ]
