# Generated by Django 5.1.4 on 2025-01-15 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0003_remove_idea_created_at_remove_idea_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='is_starred',
        ),
        migrations.AlterField(
            model_name='idea',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='idea',
            name='image',
            field=models.ImageField(upload_to='ideas/'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='interest',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='idea',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='IdeaStar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_starred', models.BooleanField(default=False)),
                ('idea', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ideas.idea')),
            ],
        ),
    ]
